/**
 * Playwright config — visual regression tests against the design canon.
 *
 * What this enforces:
 *   • 4 viewports per spec (1440 desktop / 768 tablet / 390 mobile / 375 mobile-narrow)
 *   • Chromium only — Safari/Firefox rendering differs enough that a single
 *     baseline can't cover all three; if we ever need cross-browser, we'd
 *     maintain separate baselines per engine.
 *   • Screenshot diff threshold ≤2% per the handoff (`README.md §6`).
 *     Implemented via pixelmatch in `tests/visual/utils/diff.ts` — Playwright's
 *     built-in `toHaveScreenshot` uses a per-pixel maxDiffPixelRatio that
 *     doesn't compose well with our anchor-pinned full-section captures
 *     (text antialiasing flips a bunch of pixels), so we go direct.
 *
 * Why two mobile widths:
 *   390 (iPhone 12-15 Pro standard) — typical modern iPhone, what most
 *     of our funnel visitors actually see.
 *   375 (iPhone SE / 12 mini / 13 mini / Reachability mode) — the narrow
 *     safety net. If layout survives here, it survives everywhere ≥ 375.
 *     Catches: long Russian button labels truncating, fixed-width canon
 *     cards refusing to wrap, hero H1 line-break splits going wrong.
 *
 * Where the baselines live:
 *   `tests/visual/baselines/<section>-<viewport>.png` — generated by
 *   `infra/scripts/generate-canon-baselines.sh` from `canon-source/`. Those
 *   PNGs ARE committed to the repo so PR CI sees the same reference as a
 *   local run.
 *
 * Workflow:
 *   1. Local dev edits prod code in `landing/`.
 *   2. `npm run dev` (port 3000) — Next.js HMR for visual sanity.
 *   3. `npm run test:visual` — runs this config against `localhost:3000` and
 *      compares every section against committed baselines.
 *   4. If a diff lands intentionally (design refresh): regen baselines via
 *      `infra/scripts/generate-canon-baselines.sh` and commit the PNG churn.
 */

import { defineConfig, devices } from "@playwright/test";

const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

export default defineConfig({
  testDir: "./tests/visual",
  /* 60s (was 30s): the suite runs serially (workers:1), so one slow
     navigation under CI load shouldn't trip the per-test budget. Happy path
     is ~1-3s/test, so this is headroom, not a slowdown. Pairs with the
     `domcontentloaded` navigations in the specs so we never block on a live
     Yandex Maps iframe / font CDN going idle. retries stays 0 — a flake here
     should be a real layout shift to fix, not noise to paper over. */
  timeout: 60_000,
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: process.env.CI ? [["list"], ["html", { open: "never" }]] : "list",
  use: {
    baseURL: BASE_URL,
    trace: "off",
    launchOptions: {
      args: ["--force-prefers-reduced-motion"],
    },
  },
  /* Project naming convention: `chromium-<role>-<width>`.
     The `<width>` suffix is the source-of-truth for the baseline filename
     (`<section>-<width>.png`) — see `viewportNameFromProject()` in
     `landing.spec.ts` which extracts it. Adding a new viewport = add a
     project here with the same `chromium-<role>-<width>` shape, no other
     spec-side changes required. */
  projects: [
    {
      name: "chromium-desktop-1440",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
    {
      name: "chromium-tablet-768",
      use: { ...devices["Desktop Chrome"], viewport: { width: 768, height: 1024 } },
    },
    {
      name: "chromium-mobile-390",
      use: { ...devices["Desktop Chrome"], viewport: { width: 390, height: 844 } },
    },
    {
      name: "chromium-mobile-375",
      use: { ...devices["Desktop Chrome"], viewport: { width: 375, height: 812 } },
    },
  ],
});
