/**
 * Playwright config — visual regression tests against the design canon.
 *
 * What this enforces:
 *   • 3 viewports per spec (1440 desktop / 768 tablet / 390 mobile)
 *   • Chromium only — Safari/Firefox rendering differs enough that a single
 *     baseline can't cover all three; if we ever need cross-browser, we'd
 *     maintain separate baselines per engine.
 *   • Screenshot diff threshold ≤2% per the handoff (`README.md §6`).
 *     Implemented via pixelmatch in `tests/visual/utils/diff.ts` — Playwright's
 *     built-in `toHaveScreenshot` uses a per-pixel maxDiffPixelRatio that
 *     doesn't compose well with our anchor-pinned full-section captures
 *     (text antialiasing flips a bunch of pixels), so we go direct.
 *
 * Where the baselines live:
 *   `tests/visual/baselines/<section>-<viewport>.png` — generated by
 *   `infra/scripts/generate-canon-baselines.sh` from `canon-source/`. Those
 *   PNGs ARE committed to the repo so PR CI sees the same reference as a
 *   local run.
 *
 * Workflow:
 *   1. Local dev edits prod code in `landing/`.
 *   2. `npm run dev` (port 3000) — Next.js HMR for visual sanity.
 *   3. `npm run test:visual` — runs this config against `localhost:3000` and
 *      compares every section against committed baselines.
 *   4. If a diff lands intentionally (design refresh): regen baselines via
 *      `infra/scripts/generate-canon-baselines.sh` and commit the PNG churn.
 */

import { defineConfig, devices } from "@playwright/test";

// `process.env.BASE_URL` lets CI / production-deploy verification point the
// same test suite at staging or prod without code edits. Default is local
// `next dev`.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

export default defineConfig({
  testDir: "./tests/visual",
  /* Per-test timeout — Hero with Recharts can take ~3s to settle. */
  timeout: 30_000,
  /* Don't parallelise visual tests — multiple Chromium instances on the same
     viewport can race over the canvas server in canon baseline generation,
     and serial output is much easier to read in CI logs. */
  fullyParallel: false,
  workers: 1,
  /* Retries are FORBIDDEN for visual tests — a "flake" here usually means
     a real layout shift (e.g. a font race) we want to see, not hide. */
  retries: 0,
  reporter: process.env.CI ? [["list"], ["html", { open: "never" }]] : "list",
  use: {
    baseURL: BASE_URL,
    /* Trace on first retry, but since retries=0 it never fires. Kept for
       future cross-browser expansion. */
    trace: "off",
    /* Skip animations entirely — hover lift transitions (0.18-0.2s ease-out
       per PR #85) flip pixels around card edges depending on capture timing. */
    launchOptions: {
      args: ["--force-prefers-reduced-motion"],
    },
  },
  /* Single chromium project — see note in file header. */
  projects: [
    {
      name: "chromium-desktop",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
    {
      name: "chromium-tablet",
      use: { ...devices["Desktop Chrome"], viewport: { width: 768, height: 1024 } },
    },
    {
      name: "chromium-mobile",
      use: { ...devices["Desktop Chrome"], viewport: { width: 390, height: 844 } },
    },
  ],
});
